version: '3.8'
services:
  postgres:
    image: commodorebeard/interview-data-engineer:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
